### ISSUE TITLE
Doesn't support node < 6

### ISSUE THREAD

**Issue by NickHu** [matrix-hacks/matrix-puppet-bridge#14]
Issues like this:

```
$ node index.js -r -u "http://x:8090"
/x/matrix-puppet-facebook/index.js:1
(function (exports, require, module, __filename, __dirname) { const {
                                                                    ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

are observed when trying to use these puppet bridges with old versions of node, including the latest supported by debian stable and openbsd.

As identified by @kfatehi, one approach to this might be to replicate the build step here: https://github.com/matrix-org/matrix-js-sdk/blob/master/package.json#L12

**Comment by kfatehi** [comment]
hey @NickHu i'm closing this because we are just using too many modern features and it will be a maintenance nightmare to support node < 6 -- i recommend using something node node version manager if you have to run different versions side by side.
