### ISSUE TITLE
handle attachments other than image

### ISSUE THREAD

**Issue by kfatehi** [matrix-hacks/matrix-puppet-bridge#16]
we are currently calling [sendImageMessage](https://github.com/matrix-org/matrix-js-sdk/blob/625697e0970f799dc0bfef8841a09d5d219d7939/src/client.js#L1094) for image attachments, but it's quite low-hanging fruit at this point to support the other various attachments [(msgtypes) in the spec](https://matrix.org/docs/spec/client_server/r0.2.0.html#m-room-message-msgtypes)

we should do that and simplify the bridge-apps....

ideally we can get to a point where writing a bridge-app is declarative and devoid of complex logic for parsing and handling messages and attachments.

**Comment by nr23730** [comment]
#37 solved this.
