### ISSUE TITLE
Create Matrix <-> Telegram puppet bridge via telegram.link node.js Telegram API library 

### ISSUE THREAD

**Issue by MurzNN** [matrix-hacks/matrix-puppet-bridge#30]
At now Matrix have only bot-based bridge to Telegram - [telematrix](https://github.com/SijmenSchoon/telematrix) that don't support direct chats, and [matrix-appservice-tg](https://github.com/matrix-org/matrix-appservice-tg) that is not in working state at now.

I have found [telegram.link](https://github.com/enricostara/telegram.link) node.js Telegram API library, that support all types of Telegram messages.

Will be good to implement Matrix-Telegram bridge with `telegram.link`, based on matrix-puppet-bridge project.

**Comment by nr23730** [comment]
I'm closing this now. Since 11/2017 there is tuilr/mautrix-telegram which is based on python.
However. If anyone still wants to build a Node.js bridge for telegram - feel free to do this.
