### ISSUE TITLE
Sendng message creates room but bot is not added

### ISSUE THREAD

**Issue by hooger** [matrix-hacks/matrix-puppet-bridge#51]
My problem is that when sending a message from hangouts webclient  I see it in the log, however it does not appears in Riot. Log says the bot is not invited into the room. Another hangouts chat works fine (also initiated by my message).This room originally should have been initiated by the message of the other user. Maybe that was the problem. I also see that with Facebook puppet, but there I can confirm with another user, incoming message initated room correctly. This makes me think it may be a main bridge problem, not a particular one, but not sure.

Corresponding hangouts log: https://horvathg.duckdns.org/nextcloud/index.php/s/dCxoxkYGesD94TY
Corresponding facebook log: https://horvathg.duckdns.org/nextcloud/index.php/s/w9GjLsNGKzD9TPG

Please tell me what other logs you need!
Thank you in advance!

**Comment by hooger** [comment]
As per the suggestion of @zetorian:chat.hopto.org, the following quick fix works, both with the Facebook and the Hangouts issue. The fix is the following:  

(quote begins)
- edit the package-lock.json and remove the versions from the end ot the matrix-puppet-bridge strings, should be two of them ie: github:matrix-hacks/matrix-puppet-bridge#838475340293904938493849835 to -> github:matrix-hacks/matrix-puppet-bridge,
- then edit package.json to point to the correct commit, the newest one ie: "matrix-puppet-bridge": "matrix-hacks/matrix-puppet-bridge#8a8cea3"
- then npm update and npm install.
(end quote)

**Comment by nr23730** [comment]
Solved by matrix-hacks/matrix-puppet-hangouts@3ef5eef72cdd4e0359be5cb18364abf34349a48e
